CREATE TABLE IF NOT EXISTS serial_numbers (
    serial_number CHAR(16) NOT NULL PRIMARY KEY,
    is_used TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tunes (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    polled INT UNSIGNED NOT NULL DEFAULT 0
);
